### ISSUE TITLE
Switch from windows_package to package resource to prevent warnings on each run

### ISSUE THREAD

**Issue by phwelo** [chef-cookbooks/powershell#101]
### Cookbook version
5.1.0

### Chef-client version
PS C:\Windows\system32> chef-client -v
Chef: 12.16.42

### Platform Details
Windows 2012R2

### Scenario:
Getting a warning. Probably just need to switch 'windows_package' resources with plain old 'package'
```
[2016-11-14T10:07:17-05:00] WARN: Please use the package resource available in Chef Client 12.6+.
windows_package will be removed in the next major version release
of the Windows cookbook.
```

### Steps to Reproduce:
I'm using the powershell5 recipe, but looks to be used also in powershell3.rb, powershell4.rb, as well as powershell5.rb

### Expected Result:
Just needs update before next major release of Chef

**Comment by tas50** [comment]
This is something we'll probably do after Chef 13 is released in April. It drops support for Chef < 12.6, which is still pretty popular on the Windows side of things.

**Comment by jugatsu** [comment]
This issue can be closed as we are using built-in `windows_package` resource from 12.6+.

**Comment by jugatsu** [comment]
@phwelo v6.0 version of `powershell` cookbook fixes this issue.
