### ISSUE TITLE
Kitchen Converge fails with PowerShell5 and Windows cookbook version 3.0.0

### ISSUE THREAD

**Issue by rschiefer** [chef-cookbooks/powershell#104]
### Version Info
PowerShell Cookbook v5.2.0
Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31
Microsoft Windows [Version 10.0.14393]

### Scenario:
Kitchen converge fails with the following error when running PowerShell5 recipe with Windows cookbook 3.0.0:

> [2017-03-15T18:54:32-07:00] WARN: PowerShell 2.0 is not supported or already installed on this version of Windows: 6.1.7601
>        ================================================================================
>        Recipe Compile Error in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/acme_win_web/recipes/default.rb
>        ================================================================================
>        NoMethodError
>        ————-
>        undefined method `success_codes’ for Chef::Resource::WindowsPackage
>        Platform:
>        ———
>        x64-mingw32
> 

I was able to workaround this error by constraining the Windows cookbook to < 3.0.0

http://www.dotnetcatch.com/2017/03/16/chef-tip-constrain-dependent-cookbook-versions/

**Comment by michaeltlombardi** [comment]
Just ran into this as well.

**Comment by tas50** [comment]
Fixed in master
