### ISSUE TITLE
powershell5 recipe error on 2008R2

### ISSUE THREAD

**Issue by rschiefer** [chef-cookbooks/powershell#110]
### Cookbook version
6.1.0

### Chef-client version
13.2.20

### Platform Details
Windows Server 2008R2 (6.1.7601.65536)

### Scenario:
Install PowerShell 5 using the powershell5 recipe.

### Steps to Reproduce:
Include the powershell5 recipe.

### Expected Result:
PowerShell installs successfully.

### Actual Result:
Chef::Exceptions::ResourceNotFound: resource windows_package[Windows Management Framework Core 5.1] is configured to notify resource reboot[powershell] with action reboot_now, but reboot[powershell]  cannot be found in the resource collection

**Comment by rschiefer** [comment]
Found a fix and submitting a PR.

**Comment by stuartpreston** [comment]
@rschiefer Thanks for your patience, this looks like it was released in version 6.1.1 - please if you could retest your specific scenario and open a new issue if there are still problems.

**Comment by rschiefer** [comment]
Verified.  Thanks!
