### ISSUE TITLE
Files are not copied recursively for a locally-sourced PowerShell module

### ISSUE THREAD

**Issue by nebffa** [chef-cookbooks/powershell#116]
### Steps to Reproduce:
1. Have a local PowerShell module
2. Use the `powershell_module` resource to copy it to another location.

### Expected Result:
All files in the module, as well as any files in a subfolder, are copied.

### Actual Result:
Only the files in the base directory are copied.

**Comment by smurawski** [comment]
This is probably a bug, but the better solution would be to move to PowerShell package management (PowerShellGet) (which is supported by the `powershell_package` resource in core chef (as of 12.16 and newer).

**Comment by stuartpreston** [comment]
Closing this issue due to age - in this case we are now deprecating the `powershell_module` resource from the cookbook.  Please open a new issue if you cannot accomplish your goals using the `powershell_package` and `powershell_package_source` resources.
