### ISSUE TITLE
Setting ['installation_reboot_mode'] = 'immediate_reboot' should not stop Chef run

### ISSUE THREAD

**Issue by DamonStamper** [chef-cookbooks/powershell#117]
### Cookbook version
6.1.1

### Chef-client version
12.19.36

### Platform Details
Windows 2012R2 (Vagrant image ['opentable/win-2012r2-standard-amd64-nocm'][virtualbox, 1.0.0)] )

### Scenario:
When using 'powershell::powershell5' to install a new version of powershell and setting the ['installation_reboot_mode'] attribute to 'immediate_reboot' the Chef run stops at system reboot even if there are further resources to evaluate. 

### Steps to Reproduce:
set ['installation_reboot_mode'] attribute to 'immediate_reboot'.

### Expected Result:
Chef reboots the computer and continues with the rest of its evaluation.

### Actual Result:
Chef reboots the computer and stops its evaluation thus requiring a second run.

### Notes:
The [sql_server](https://github.com/chef-cookbooks/sql_server) cookbook's 'server' recipe allows a reboot mid-Chef run. That functionality should be also implemented in the powershell cookbook.

Applicable [code](https://github.com/chef-cookbooks/sql_server/blob/master/recipes/server.rb#L75) in sql_server cookbook.

**Comment by iennae** [comment]
The behavior is working as expected. The sql_server doesn't reboot mid-Chef run. It sends a notification to reboot that occurs at the end of a successful chef run. 

https://docs.chef.io/resource_reboot.html (request_reboot explanation)

immediate_reboot is going to reboot the system immediately. If you are trying to replicate the sql_server functionality, try the delayed_reboot option.
