### ISSUE TITLE
Powershell install doesn't trigger reboot

### ISSUE THREAD

**Issue by palfrey** [chef-cookbooks/powershell#14]
When some of the packages for a newer Powershell version gets installed, a Windows reboot is required before it gets picked up, but the Powershell cookbook never uses windows_reboot, so that's hard to detect from outside.

I'd expect something like the following:

```Ruby
windows_reboot 60 do
  reason 'new powershell version'
  action :nothing
end
```

and then a `notifies :request, 'windows_reboot[60]'` in the relevant `windows_package` item.

**Comment by tjnicholas** [comment]
With reference to @christrotter's comment, it looks like master is 60 commits ahead of the 3.0.7 tag. 

Can we get a new version released/tagged? Lots of good stuff in those 60 commits... @NimishaS

**Comment by NimishaS** [comment]
@tjnicholas , yes we'll release the changes.

**Comment by NimishaS** [comment]
@palfrey , @christrotter  Reboot code has been added to all powershell cookbooks in the master branch. It's not released yet. Please use master branch code till the release.

**Comment by tas50** [comment]
Closing this out since the commit was merged.  We'll try to get a release out shortly.
