### ISSUE TITLE
powershell_module doesn't work on Server Core

### ISSUE THREAD

**Issue by gadgetmg** [chef-cookbooks/powershell#45]
The powershell_module provider uses PowerShell code that relies on things not present in Server Core. The code relies on the shell, which doesn't exist in Server Core. Also, to run "Invoke-WebRequest" in Server Core, you have to pass the "-UseBasicParsing" argument.

**Comment by RyanJarv** [comment]
Made this pull request which resolves this issue.

https://github.com/chef-cookbooks/powershell/pull/60

**Comment by smurawski** [comment]
Closed by #60
