### ISSUE TITLE
Correct the PowerShell 5 version for WMF5 February 2015 

### ISSUE THREAD

**Issue by bheuvel** [chef-cookbooks/powershell#52]
WMF5 Nov 2014 : 5.0.9701.0
WMF5 Feb 2015 : 5.0.10018.0
WMF5 Apr 2015 : 5.0.10105.0

As Feb is referenced here, the version needs to be corrected or else the install keeps installing each chef-run (guard not basically not effective)

Corrected with PR #46

**Comment by tas50** [comment]
#46 has been merged
