### ISSUE TITLE
Powershell 5 is supported for Windows 2008 R2 SP1

### ISSUE THREAD

**Issue by lbn-aaio-team** [chef-cookbooks/powershell#59]
Hello,

Could you add Windows 2008 R2 SP1 to the "supported" list for Powershell 5.0 ?

http://blogs.msdn.com/b/powershell/archive/2015/08/31/windows-management-framework-5-0-production-preview-is-now-available.aspx
https://www.microsoft.com/en-us/download/details.aspx?id=46889

As MS says:

Supported Operating System
Windows 7, Windows 8.1, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2
Windows Server 2012 R2
Windows 8.1 Pro
Windows 8.1 Enterprise
Windows Server 2012
Windows 7 SP1
Windows Server 2008 R2 SP1

**IMPORTANT**
Systems that are running the following server applications should not run Windows Management Framework 5.0 at this time.
System Center 2012 Configuration Manager (not including SP1)
Windows Small Business Server 2011 Standard

WMF 5.0 requires Microsoft .NET Framework 4.5. You can install Microsoft .NET Framework 4.5 from the Microsoft Download Center.

**Comment by it-praktyk** [comment]
Hi!

I agree, other versions Windows systems are also supported by Windows Management Framework 5.0 Production Preview.

The current download link is https://www.microsoft.com/en-us/download/details.aspx?id=48729 .

**Comment by smurawski** [comment]
Installing WMF 5 on Server 2008 R2 is now supported via this cookbook with [v3.2.0](https://github.com/chef-cookbooks/powershell/releases/tag/v3.2.0)
