### ISSUE TITLE
Problem using cookbook from github or supermarket

### ISSUE THREAD

**Issue by gfediere** [chef-cookbooks/powershell#62]
Hi,

I'm using this cookbook trhough supermarket but problem is powershell version isn't: 5.0.10514.6 (as mentionned in github attribute for this cookbook). When downloading the zip file from supermarket and open default attribute, there is no node[powershell][powershell5][version] and it's using: WindowsBlue-KB3037315-x86.msu (version 5.0.10018.0)

**Comment by smurawski** [comment]
There will be a new release of this cookbook early next week.

**Comment by smurawski** [comment]
Released earlier this week.
