### ISSUE TITLE
Add support for the WMF 4 Updates on 2012/2008 R2

### ISSUE THREAD

**Issue by smurawski** [chef-cookbooks/powershell#78]
Just released patches for WMF 4 - http://blogs.msdn.com/b/powershell/archive/2016/01/19/windows-management-framework-wmf-4-0-update-now-available-for-windows-server-2012-windows-server-2008-r2-sp1-and-windows-7-sp1.aspx

**Comment by jugatsu** [comment]
@smurawski I didn't find any downloadable links for this updates. But we can get them via `Get-Hotfix` cmdlet. For example
```powershell
Get-HotFix -ID KB3119938
```
https://raw.githubusercontent.com/PowerShell/SILDeploymentHelper/431dc8e6a0a566ac4a7a301caa121d6fc42ab002/SILDeploymentHelper.psm1

Also we can move geeting hotfixes to separate library helper.

**Comment by stuartpreston** [comment]
Closing this due to age - for most people this patch would now be applied in any image, and WMF 5 is the recommendation anyway.
