### ISSUE TITLE
Undefined node attribute or method `<' on `node'

### ISSUE THREAD

**Issue by tho-wa** [chef-cookbooks/powershell#84]
I get following error in powershell4: 
Undefined node attribute or method `<' on `node'

affected code line:
fail 'Attribute ms_dotnet.v4.version is not configured to install .NET4.5 as required for Powershell4' if node['ms_dotnet']['v4']['version'] < '4.5'

**Comment by jdgoins** [comment]
Hey @tho-wa, you need to include the ms_dotnet cookbook to install .NET 4.5. Try including the below before you run the powershell cookbook in your recipe.
`node.default['ms_dotnet']['v4']['version'] = '4.5.2'
include_recipe 'ms_dotnet::ms_dotnet4'`

**Comment by tas50** [comment]
As @jdgoins said this error shouldn't be seen if the ms_dotnet cookbook is on your server or local workstation. Can you confirm that's the case and open it back up if you still see the problem
