### ISSUE TITLE
Clarify use of installation recipes in the README

### ISSUE THREAD

**Issue by tpetchel** [chef-cookbooks/powershell#85]
In the README, we say things like:

```
### powershell4

Include the `powershell4` recipe in a run list, to install PowerShell 4.0 is installed on applicable platforms. If a platform is not supported or if it already includes PowerShell 4.0, an exception will be raised.
```

But it looks like you just get a warning. 

```
[2016-03-30T14:27:03+00:00] WARN: PowerShell 4.0 is not supported or already installed on this version of Windows: 6.3.9600
```

https://github.com/chef-cookbooks/powershell/blob/master/recipes/powershell4.rb#L52

It also looks like you just get a warning if the platform is not supported.

https://github.com/chef-cookbooks/powershell/blob/master/recipes/powershell4.rb#L56

I might simply remove the statement "If a platform is not supported or if it already includes PowerShell 4.0, an exception will be raised." I would have to see if the same logic is used by the other installation recipes.

I felt strongly enough to file an issue because exception implies failure to me, like I would have to write a guard around it. Using this recipe is much easier than doing that. ;)

**Comment by tas50** [comment]
I've clarified the behavior in the readme
