### ISSUE TITLE
(low pri) deprecated warning

### ISSUE THREAD

**Issue by vinyar** [chef-cookbooks/powershell#90]
Issue:
Platform:
Kitchen (v1.9.1)
wind2012-r2
Chef Client, version 12.10.24
box: mwrock/Windows2012R2

       Deprecated features used!
         The on_platforms option to node_map has been deprecated at 1 location:
           - C:/Users/vagrant/AppData/Local/Temp/kitchen/cookbooks/powershell/libraries/powershell_module_resource.rb:25:in `<class:PowershellModule>'
         Using an LWRP provider by its name (WindowsFeatureDism) directly is no longer supported in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead. at 1 location:
           - C:\Users\vagrant\AppData\Local\Temp\kitchen\cookbooks\windows\resources\feature.rb:32:in `initialize'

(sorry no time to work on it now, figured i'll add the bug anyway)

**Comment by vinyar** [comment]
oh, looks like there is a PR already: https://github.com/chef-cookbooks/powershell/pull/89

**Comment by smurawski** [comment]
@vinyar The WindowsFeatureDism deprecation warning is out of the windows cookbook, not this one. #89 deals with the warning in this cookbook.
